<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/order/_index.blade.php" was generated by ProBot AI.
* Date: 2/21/2025 12:56:35 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage Order')
@section('style')


@endsection
@section('page')
<a href="{{route('orders.create')}}">New Order</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Customer Id</th>
			<th>User Id</th>
			<th>Total Amount</th>
			<th>Discount</th>
			<th>Status Id</th>
			<th>Order Date</th>
			<th>Delivery Date</th>
			<th>Created At</th>
			<th>Updated At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($orders as $order)
		<tr>
			<td>{{$order->id}}</td>
			<td>{{$order->customer_id}}</td>
			<td>{{$order->user_id}}</td>
			<td>{{$order->total_amount}}</td>
			<td>{{$order->discount}}</td>
			<td>{{$order->status_id}}</td>
			<td>{{$order->order_date}}</td>
			<td>{{$order->delivery_date}}</td>
			<td>{{$order->created_at}}</td>
			<td>{{$order->updated_at}}</td>

			<td>
			<form action = "{{route('orders.destroy',$order->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('orders.show',$order->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('orders.edit',$order->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
