<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/restable/_index.blade.php" was generated by ProBot AI.
* Date: 3/11/2025 10:47:29 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage ResTable')
@section('style')


@endsection
@section('page')
<a href="{{route('restables.create')}}">New ResTable</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Table Number</th>
			<th>Capacity</th>
			<th>Status</th>
			<th>Created At</th>
			<th>Updated At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($restables as $restable)
		<tr>
			<td>{{$restable->id}}</td>
			<td>{{$restable->table_number}}</td>
			<td>{{$restable->capacity}}</td>
			<td>{{$restable->status}}</td>
			<td>{{$restable->created_at}}</td>
			<td>{{$restable->updated_at}}</td>

			<td>
			<form action = "{{route('restables.destroy',$restable->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('restables.show',$restable->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('restables.edit',$restable->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
