<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/restable/_show.blade.php" was generated by ProBot AI.
* Date: 3/11/2025 10:47:29 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show ResTable')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('restables.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$restable->id}}</td></tr>
		<tr><th>Table Number</th><td>{{$restable->table_number}}</td></tr>
		<tr><th>Capacity</th><td>{{$restable->capacity}}</td></tr>
		<tr><th>Status</th><td>{{$restable->status}}</td></tr>
		<tr><th>Created At</th><td>{{$restable->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$restable->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
