<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/restable/_edit.blade.php" was generated by ProBot AI.
* Date: 3/5/2025 10:53:53 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Edit ResTable')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('restables.index')}}">Manage</a>
<form action="{{route('restables.update',$restable)}}" method ="post" enctype="multipart/form-data">
@csrf
@method("PUT")
<div class="row mb-3">
	<label for="table_number" class="col-sm-2 col-form-label">Table Number</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="table_number" value="{{$restable->table_number}}" id="table_number" placeholder="Table Number">
	</div>
</div>
<div class="row mb-3">
	<label for="capacity" class="col-sm-2 col-form-label">Capacity</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="capacity" value="{{$restable->capacity}}" id="capacity" placeholder="Capacity">
	</div>
</div>

<button type="submit" class="btn btn-primary">Save Change</button>
</form>
@endsection
@section('script')


@endsection
