<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/product/_edit.blade.php" was generated by ProBot AI.
* Date: 2/23/2025 10:15:46 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Edit Product')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('erp_products.index')}}">Manage</a>
<form action="{{route('erp_products.edit',$product)}}" method ="post" enctype="multipart/form-data">
@csrf
@method("PUT")
<div class="row mb-3">
	<label for="name" class="col-sm-2 col-form-label">Name</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="name" value="{{$product->name}}" id="name" placeholder="Name">
	</div>
</div>
<div class="row mb-3">
	<label for="category_id" class="col-sm-2 col-form-label">Category</label>
	<div class="col-sm-10">
		<select class="form-control" name="category_id" id="category_id">
			@foreach($categories as $category)
				@if($category->id==$product->category_id)
					<option value="{{$category->id}}" selected>{{$category->name}}</option>
				@else
					<option value="{{$category->id}}">{{$category->name}}</option>
				@endif
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="price" class="col-sm-2 col-form-label">Price</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="price" value="{{$product->price}}" id="price" placeholder="Price">
	</div>
</div>
<div class="row mb-3">
	<label for="description" class="col-sm-2 col-form-label">Description</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="description" value="{{$product->description}}" id="description" placeholder="Description">
	</div>
</div>
<div class="row mb-3">
	<label for="photo" class="col-sm-2 col-form-label">Photo</label>
	<div class="col-sm-10">
        @if ($product->photo)
        <img width="100" src="{{ asset('storage/' . $product->photo) }}" alt="{{ $product->name }}" class="img-thumbnail mb-2">
    @else
        <p>No photo available.</p>
    @endif
		<input type = "file" class="form-control" name="photo"  id="photo" placeholder="Photo">
        @error('photo')
        <span style="color: red">{{ $message }}</span>
    @enderror
	</div>
</div>

{{-- <div class="row mb-3">
	<label for="stock_quantity" class="col-sm-2 col-form-label">Stock Quantity</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="stock_quantity" value="{{$product->stock_quantity}}" id="stock_quantity" placeholder="Stock Quantity">
	</div>
</div> --}}
{{-- <div class="row mb-3">
	<label for="reorder_level" class="col-sm-2 col-form-label">Reorder Level</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="reorder_level" value="{{$product->reorder_level}}" id="reorder_level" placeholder="Reorder Level">
	</div> --}}
</div>

<button type="submit" class="btn btn-primary">Save Change</button>
</form>
@endsection
@section('script')


@endsection
