<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/orderdetail/_show.blade.php" was generated by ProBot AI.
* Date: 2/18/2025 11:08:02 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show OrderDetail')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('orderdetails.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>

</tbody>
</table>
@endsection
@section('script')


@endsection
