<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/orderdetail/_edit.blade.php" was generated by ProBot AI.
* Date: 2/20/2025 12:11:33 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Edit OrderDetail')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('orderdetails.index')}}">Manage</a>
<form action="{{route('orderdetails.update',$orderdetail)}}" method ="post" enctype="multipart/form-data">
@csrf
@method("PUT")
<div class="row mb-3">
	<label for="order_id" class="col-sm-2 col-form-label">Order</label>
	<div class="col-sm-10">
		<select class="form-control" name="order_id" id="order_id">
			@foreach($orders as $order)
				@if($order->id==$orderdetail->order_id)
					<option value="{{$order->id}}" selected>{{$order->name}}</option>
				@else
					<option value="{{$order->id}}">{{$order->name}}</option>
				@endif
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="menu_item_id" class="col-sm-2 col-form-label">Menu_Item</label>
	<div class="col-sm-10">
		<select class="form-control" name="menu_item_id" id="menu_item_id">
			@foreach($menu_items as $menu_item)
				@if($menu_item->id==$orderdetail->menu_item_id)
					<option value="{{$menu_item->id}}" selected>{{$menu_item->name}}</option>
				@else
					<option value="{{$menu_item->id}}">{{$menu_item->name}}</option>
				@endif
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="quantity" class="col-sm-2 col-form-label">Quantity</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="quantity" value="{{$orderdetail->quantity}}" id="quantity" placeholder="Quantity">
	</div>
</div>
<div class="row mb-3">
	<label for="price" class="col-sm-2 col-form-label">Price</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="price" value="{{$orderdetail->price}}" id="price" placeholder="Price">
	</div>
</div>

<button type="submit" class="btn btn-primary">Save Change</button>
</form>
@endsection
@section('script')


@endsection
