<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/orderdetail/_index.blade.php" was generated by ProBot AI.
* Date: 2/20/2025 12:11:33 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage OrderDetail')
@section('style')


@endsection
@section('page')
<a href="{{route('orderdetails.create')}}">New OrderDetail</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Order Id</th>
			<th>Menu Item Id</th>
			<th>Quantity</th>
			<th>Price</th>
			<th>Created At</th>
			<th>Updated At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($orderdetails as $orderdetail)
		<tr>
			<td>{{$orderdetail->id}}</td>
			<td>{{$orderdetail->order_id}}</td>
			<td>{{$orderdetail->menu_item_id}}</td>
			<td>{{$orderdetail->quantity}}</td>
			<td>{{$orderdetail->price}}</td>
			<td>{{$orderdetail->created_at}}</td>
			<td>{{$orderdetail->updated_at}}</td>

			<td>
			<form action = "{{route('orderdetails.destroy',$orderdetail->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('orderdetails.show',$orderdetail->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('orderdetails.edit',$orderdetail->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
