<?php
/*
 * ProBot Version: 3.0
 * Laravel Version: 10x
 * Description: This source file "resources/views/role/_edit.blade.php" was generated by ProBot AI.
 * Date: 2/20/2025 12:11:00 AM
 * Contact: towhid1@outlook.com
 */
?>
@extends('layout.erp.app')
@section('title', 'Edit Role')
@section('style')


@endsection
@section('page')
    <a class='btn btn-success' href="{{ route('roles.index') }}">Manage</a>
    <form action="{{ route('roles.update', $role) }}" method ="post" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <div class="row mb-3">
            <label for="position" class="col-sm-2 col-form-label">Position</label>
            <div class="col-sm-10">
                <input type = "text" class="form-control" name="position" value="{{ $role->position }}" id="position"
                    placeholder="Position">
            </div>
        </div>
        <div class="row mb-3">
            <label for="name" class="col-sm-2 col-form-label">Name</label>
            <div class="col-sm-10">
                <input type = "text" class="form-control" name="name" value="{{ $role->name }}" id="name"
                    placeholder="Name">
            </div>
        </div>
        <div class="row mb-3">
            <label for="photo" class="col-sm-2 col-form-label">Photo</label>
            @if ($role->photo)
                <img width="100" src="{{ asset('storage/' . $role->photo) }}" alt="{{ $role->name }}"
                    class="img-thumbnail mb-2">
            @else
                <p>No photo available.</p>
            @endif
            <input type="file" class="form-control" name="photo">
            @error('photo')
                <span style="color: red">{{ $message }}</span>
            @enderror
        </div>

        <button type="submit" class="btn btn-primary">Save Change</button>
    </form>
@endsection
@section('script')


@endsection
