<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/role/_index.blade.php" was generated by ProBot AI.
* Date: 2/20/2025 12:11:00 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage Role')
@section('style')


@endsection
@section('page')
<a href="{{route('roles.create')}}">New Role</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Position</th>
			<th>Name</th>
			<th>Photo</th>
			<th>Created At</th>
			<th>Updated At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($roles as $role)
		<tr>
			<td>{{$role->id}}</td>
			<td>{{$role->position}}</td>
			<td>{{$role->name}}</td>
			<td><img src="{{asset('img/'.$role->photo)}}" width="100" /></td>
			<td>{{$role->created_at}}</td>
			<td>{{$role->updated_at}}</td>

			<td>
			<form action = "{{route('roles.destroy',$role->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('roles.show',$role->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('roles.edit',$role->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
