<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/staff/_edit.blade.php" was generated by ProBot AI.
* Date: 2/21/2025 12:54:57 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Edit Staff')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('staffs.index')}}">Manage</a>
<form action="{{route('staffs.update',$staff)}}" method ="post" enctype="multipart/form-data">
@csrf
@method("PUT")
<div class="row mb-3">
	<label for="name" class="col-sm-2 col-form-label">Name</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="name" value="{{$staff->name}}" id="name" placeholder="Name">
	</div>
</div>
<div class="row mb-3">
	<label for="photo" class="col-sm-2 col-form-label">Photo</label>
	<div class="col-sm-10">
		<input type = "file" class="form-control" name="photo"  id="photo" placeholder="Photo">
	</div>
</div>
<div class="row mb-3">
	<label for="phone" class="col-sm-2 col-form-label">Phone</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="phone" value="{{$staff->phone}}" id="phone" placeholder="Phone">
	</div>
</div>
<div class="row mb-3">
	<label for="email" class="col-sm-2 col-form-label">Email</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="email" value="{{$staff->email}}" id="email" placeholder="Email">
	</div>
</div>
<div class="row mb-3">
	<label for="position" class="col-sm-2 col-form-label">Position</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="position" value="{{$staff->position}}" id="position" placeholder="Position">
	</div>
</div>
<div class="row mb-3">
	<label for="status" class="col-sm-2 col-form-label">Status</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="status" value="{{$staff->status}}" id="status" placeholder="Status">
	</div>
</div>

<button type="submit" class="btn btn-primary">Save Change</button>
</form>
@endsection
@section('script')


@endsection
