<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/staff/_index.blade.php" was generated by ProBot AI.
* Date: 2/21/2025 12:54:57 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage Staff')
@section('style')


@endsection
@section('page')
<a href="{{route('staffs.create')}}">New Staff</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Name</th>
			<th>Photo</th>
			<th>Phone</th>
			<th>Email</th>
			<th>Position</th>
			<th>Status</th>
			<th>Created At</th>
			<th>Updated At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($staffs as $staff)
		<tr>
			<td>{{$staff->id}}</td>
			<td>{{$staff->name}}</td>
			<td><img src="{{asset('img/'.$staff->photo)}}" width="100" /></td>
			<td>{{$staff->phone}}</td>
			<td>{{$staff->email}}</td>
			<td>{{$staff->position}}</td>
			<td>{{$staff->status}}</td>
			<td>{{$staff->created_at}}</td>
			<td>{{$staff->updated_at}}</td>

			<td>
			<form action = "{{route('staffs.destroy',$staff->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('staffs.show',$staff->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('staffs.edit',$staff->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
