<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/staff/_show.blade.php" was generated by ProBot AI.
* Date: 2/21/2025 12:54:57 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show Staff')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('staffs.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$staff->id}}</td></tr>
		<tr><th>Name</th><td>{{$staff->name}}</td></tr>
		<tr><th>Photo</th><td><img src="{{asset('img/'.$staff->photo)}}" width="100" /></td></tr>
		<tr><th>Phone</th><td>{{$staff->phone}}</td></tr>
		<tr><th>Email</th><td>{{$staff->email}}</td></tr>
		<tr><th>Position</th><td>{{$staff->position}}</td></tr>
		<tr><th>Status</th><td>{{$staff->status}}</td></tr>
		<tr><th>Created At</th><td>{{$staff->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$staff->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
