<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/customerreview/_edit.blade.php" was generated by ProBot AI.
* Date: 2/21/2025 12:55:32 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Edit CustomerReview')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('customerreviews.index')}}">Manage</a>
<form action="{{route('customerreviews.update',$customerreview)}}" method ="post" enctype="multipart/form-data">
@csrf
@method("PUT")
<div class="row mb-3">
	<label for="customer_id" class="col-sm-2 col-form-label">Customer</label>
	<div class="col-sm-10">
		<select class="form-control" name="customer_id" id="customer_id">
			@foreach($customers as $customer)
				@if($customer->id==$customerreview->customer_id)
					<option value="{{$customer->id}}" selected>{{$customer->name}}</option>
				@else
					<option value="{{$customer->id}}">{{$customer->name}}</option>
				@endif
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="product_id" class="col-sm-2 col-form-label">Product</label>
	<div class="col-sm-10">
		<select class="form-control" name="product_id" id="product_id">
			@foreach($products as $product)
				@if($product->id==$customerreview->product_id)
					<option value="{{$product->id}}" selected>{{$product->name}}</option>
				@else
					<option value="{{$product->id}}">{{$product->name}}</option>
				@endif
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="order_id" class="col-sm-2 col-form-label">Order</label>
	<div class="col-sm-10">
		<select class="form-control" name="order_id" id="order_id">
			@foreach($orders as $order)
				@if($order->id==$customerreview->order_id)
					<option value="{{$order->id}}" selected>{{$order->name}}</option>
				@else
					<option value="{{$order->id}}">{{$order->name}}</option>
				@endif
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="rating" class="col-sm-2 col-form-label">Rating</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="rating" value="{{$customerreview->rating}}" id="rating" placeholder="Rating">
	</div>
</div>
<div class="row mb-3">
	<label for="review" class="col-sm-2 col-form-label">Review</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="review" value="{{$customerreview->review}}" id="review" placeholder="Review">
	</div>
</div>

<button type="submit" class="btn btn-primary">Save Change</button>
</form>
@endsection
@section('script')


@endsection
