<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/customerreview/_index.blade.php" was generated by ProBot AI.
* Date: 2/21/2025 12:55:32 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage CustomerReview')
@section('style')


@endsection
@section('page')
<a href="{{route('customerreviews.create')}}">New CustomerReview</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Customer Id</th>
			<th>Product Id</th>
			<th>Order Id</th>
			<th>Rating</th>
			<th>Review</th>
			<th>Created At</th>
			<th>Updated At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($customerreviews as $customerreview)
		<tr>
			<td>{{$customerreview->id}}</td>
			<td>{{$customerreview->customer_id}}</td>
			<td>{{$customerreview->product_id}}</td>
			<td>{{$customerreview->order_id}}</td>
			<td>{{$customerreview->rating}}</td>
			<td>{{$customerreview->review}}</td>
			<td>{{$customerreview->created_at}}</td>
			<td>{{$customerreview->updated_at}}</td>

			<td>
			<form action = "{{route('customerreviews.destroy',$customerreview->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('customerreviews.show',$customerreview->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('customerreviews.edit',$customerreview->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
