<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/customerreview/_show.blade.php" was generated by ProBot AI.
* Date: 2/21/2025 12:55:32 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show CustomerReview')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('customerreviews.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$customerreview->id}}</td></tr>
		<tr><th>Customer Id</th><td>{{$customerreview->customer_id}}</td></tr>
		<tr><th>Product Id</th><td>{{$customerreview->product_id}}</td></tr>
		<tr><th>Order Id</th><td>{{$customerreview->order_id}}</td></tr>
		<tr><th>Rating</th><td>{{$customerreview->rating}}</td></tr>
		<tr><th>Review</th><td>{{$customerreview->review}}</td></tr>
		<tr><th>Created At</th><td>{{$customerreview->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$customerreview->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
