<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/supplier/_index.blade.php" was generated by ProBot AI.
* Date: 2/19/2025 11:51:42 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage Supplier')
@section('style')


@endsection
@section('page')
<a href="{{route('suppliers.create')}}">New Supplier</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Name</th>
			<th>Contact Person</th>
			<th>Phone</th>
			<th>Email</th>
			<th>Address</th>
			<th>Created At</th>
			<th>Updated At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($suppliers as $supplier)
		<tr>
			<td>{{$supplier->id}}</td>
			<td>{{$supplier->name}}</td>
			<td>{{$supplier->contact_person}}</td>
			<td>{{$supplier->phone}}</td>
			<td>{{$supplier->email}}</td>
			<td>{{$supplier->address}}</td>
			<td>{{$supplier->created_at}}</td>
			<td>{{$supplier->updated_at}}</td>

			<td>
			<form action = "{{route('suppliers.destroy',$supplier->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('suppliers.show',$supplier->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('suppliers.edit',$supplier->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
