<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/user/_show.blade.php" was generated by ProBot AI.
* Date: 3/1/2025 12:58:44 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show User')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('users.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$user->id}}</td></tr>
		<tr><th>Name</th><td>{{$user->name}}</td></tr>
		<tr><th>Email</th><td>{{$user->email}}</td></tr>
		<tr><th>Role Id</th><td>{{$user->role_id}}</td></tr>
		<tr><th>Email Verified At</th><td>{{$user->email_verified_at}}</td></tr>
		<tr><th>Password</th><td>{{$user->password}}</td></tr>
		<tr><th>Remember Token</th><td>{{$user->remember_token}}</td></tr>
		<tr><th>Created At</th><td>{{$user->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$user->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
