<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/paymentstatu/_index.blade.php" was generated by ProBot AI.
* Date: 2/21/2025 12:59:19 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage PaymentStatu')
@section('style')


@endsection
@section('page')
<a href="{{route('paymentstatus.create')}}">New PaymentStatu</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Status</th>
			<th>Description</th>
			<th>Created At</th>
			<th>Updated At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($paymentstatus as $paymentstatu)
		<tr>
			<td>{{$paymentstatu->id}}</td>
			<td>{{$paymentstatu->status}}</td>
			<td>{{$paymentstatu->description}}</td>
			<td>{{$paymentstatu->created_at}}</td>
			<td>{{$paymentstatu->updated_at}}</td>

			<td>
			<form action = "{{route('paymentstatus.destroy',$paymentstatu->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('paymentstatus.show',$paymentstatu->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('paymentstatus.edit',$paymentstatu->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
