<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/paymentstatu/_show.blade.php" was generated by ProBot AI.
* Date: 2/21/2025 12:59:19 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show PaymentStatu')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('paymentstatus.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$paymentstatu->id}}</td></tr>
		<tr><th>Status</th><td>{{$paymentstatu->status}}</td></tr>
		<tr><th>Description</th><td>{{$paymentstatu->description}}</td></tr>
		<tr><th>Created At</th><td>{{$paymentstatu->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$paymentstatu->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
