<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/customer/_edit.blade.php" was generated by ProBot AI.
* Date: 3/3/2025 11:00:12 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Edit Customer')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('customers.index')}}">Manage</a>
<form action="{{route('customers.update',$customer)}}" method ="post" enctype="multipart/form-data">
@csrf
@method("PUT")
<div class="row mb-3">
	<label for="name" class="col-sm-2 col-form-label">Name</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="name" value="{{$customer->name}}" id="name" placeholder="Name">
	</div>
</div>
<div class="row mb-3">
	<label for="phone" class="col-sm-2 col-form-label">Phone</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="phone" value="{{$customer->phone}}" id="phone" placeholder="Phone">
	</div>
</div>
<div class="row mb-3">
	<label for="email" class="col-sm-2 col-form-label">Email</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="email" value="{{$customer->email}}" id="email" placeholder="Email">
	</div>
</div>
<div class="row mb-3">
	<label for="address" class="col-sm-2 col-form-label">Address</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="address" value="{{$customer->address}}" id="address" placeholder="Address">
	</div>
</div>
<div class="row mb-3">
	<label for="city" class="col-sm-2 col-form-label">City</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="city" value="{{$customer->city}}" id="city" placeholder="City">
	</div>
</div>
<div class="row mb-3">
	<label for="post_code" class="col-sm-2 col-form-label">Post Code</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="post_code" value="{{$customer->post_code}}" id="post_code" placeholder="Post Code">
	</div>
</div>

<button type="submit" class="btn btn-primary">Save Change</button>
</form>
@endsection
@section('script')


@endsection
