<?php
/*
 * ProBot Version: 3.0
 * Laravel Version: 10x
 * Description: This source file "resources/views/orderitem/_show.blade.php" was generated by ProBot AI.
 * Date: 2/21/2025 12:56:59 AM
 * Contact: towhid1@outlook.com
 */
?>
@extends('layout.erp.app')
@section('title', 'Show OrderItem')
@section('style')


@endsection
@section('page')
    <a class='btn btn-success' href="{{ route('orderitems.index') }}">Manage</a>
    <table class='table table-striped text-nowrap'>
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ $orderitem->id }}</td>
            </tr>
            <tr>
                <th>Order Id</th>
                <td>{{ $orderitem->order_id }}</td>
            </tr>
            <tr>
                <th>Product Id</th>
                <td>{{ $orderitem->product_id }}</td>
            </tr>
            <tr>
                <th>Quantity</th>
                <td>{{ $orderitem->quantity }}</td>
            </tr>
            <tr>
                <th>Price</th>
                <td>{{ $orderitem->price }}</td>
            </tr>
            <tr>
                <th>Created At</th>
                <td>{{ $orderitem->created_at }}</td>
            </tr>
            <tr>
                <th>Updated At</th>
                <td>{{ $orderitem->updated_at }}</td>
            </tr>

        </tbody>
    </table>
@endsection
@section('script')


@endsection
