<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/restableduration/_edit.blade.php" was generated by ProBot AI.
* Date: 3/12/2025 10:00:19 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Edit RestableDuration')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('restabledurations.index')}}">Manage</a>
<form action="{{route('restabledurations.update',$restableduration)}}" method ="post" enctype="multipart/form-data">
@csrf
@method("PUT")
<div class="row mb-3">
	<label for="res_table_id" class="col-sm-2 col-form-label">Res_Table</label>
	<div class="col-sm-10">
		<select class="form-control" name="res_table_id" id="res_table_id">
			@foreach($res_tables as $res_table)
				@if($res_table->id==$restableduration->res_table_id)
					<option value="{{$res_table->id}}" selected>{{$res_table->name}}</option>
				@else
					<option value="{{$res_table->id}}">{{$res_table->name}}</option>
				@endif
			@endforeach
		</select>
	</div>
</div>

<button type="submit" class="btn btn-primary">Save Change</button>
</form>
@endsection
@section('script')


@endsection
