<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/restableduration/_index.blade.php" was generated by ProBot AI.
* Date: 3/12/2025 10:00:19 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage RestableDuration')
@section('style')


@endsection
@section('page')
<a href="{{route('restabledurations.create')}}">New RestableDuration</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Res Table Id</th>
			<th>Start Time</th>
			<th>End Time</th>
			<th>Created At</th>
			<th>Updated At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($restabledurations as $restableduration)
		<tr>
			<td>{{$restableduration->id}}</td>
			<td>{{$restableduration->res_table_id}}</td>
			<td>{{$restableduration->start_time}}</td>
			<td>{{$restableduration->end_time}}</td>
			<td>{{$restableduration->created_at}}</td>
			<td>{{$restableduration->updated_at}}</td>

			<td>
			<form action = "{{route('restabledurations.destroy',$restableduration->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('restabledurations.show',$restableduration->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('restabledurations.edit',$restableduration->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
