<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/restableduration/_show.blade.php" was generated by ProBot AI.
* Date: 3/12/2025 10:00:19 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show RestableDuration')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('restabledurations.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$restableduration->id}}</td></tr>
		<tr><th>Res Table Id</th><td>{{$restableduration->res_table_id}}</td></tr>
		<tr><th>Start Time</th><td>{{$restableduration->start_time}}</td></tr>
		<tr><th>End Time</th><td>{{$restableduration->end_time}}</td></tr>
		<tr><th>Created At</th><td>{{$restableduration->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$restableduration->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
