<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/menu/_index.blade.php" was generated by ProBot AI.
* Date: 2/21/2025 1:14:58 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage Menu')
@section('style')


@endsection
@section('page')
<a href="{{route('menus.create')}}">New Menu</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Name</th>
			{{-- <th>Description</th> --}}
			<th>Is Active</th>
			<th>Created At</th>
			<th>Updated At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($menus as $menu)
		<tr>
			<td>{{$menu->id}}</td>
			<td>{{$menu->name}}</td>
			{{-- <td>{{$menu->description}}</td> --}}
			<td>{{$menu->is_active}}</td>
			<td>{{$menu->created_at}}</td>
			<td>{{$menu->updated_at}}</td>

			<td>
			<form action = "{{route('menus.destroy',$menu->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('menus.show',$menu->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('menus.edit',$menu->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
