<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/menu/_show.blade.php" was generated by ProBot AI.
* Date: 2/21/2025 1:14:58 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show Menu')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('menus.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$menu->id}}</td></tr>
		<tr><th>Name</th><td>{{$menu->name}}</td></tr>
		<tr><th>Description</th><td>{{$menu->description}}</td></tr>
		<tr><th>Is Active</th><td>{{$menu->is_active}}</td></tr>
		<tr><th>Created At</th><td>{{$menu->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$menu->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
