<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/reservation/_create.blade.php" was generated by ProBot AI.
* Date: 2/27/2025 12:25:07 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Create Reservation')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('reservations.index')}}">Manage</a>
<form action="{{route('reservations.store')}}" method ="post" enctype="multipart/form-data">
@csrf
<div class="row mb-3">
	<label for="customer_id" class="col-sm-2 col-form-label">Customer</label>
	<div class="col-sm-10">
		<select class="form-control" name="customer_id" id="customer_id">
			@foreach($customers as $customer)
				<option value="{{$customer->id}}">{{$customer->name}}</option>
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="booking_name" class="col-sm-2 col-form-label">Booking Name</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="booking_name" id="booking_name" placeholder="Booking Name">
	</div>
</div>
<div class="row mb-3">
	<label for="phone" class="col-sm-2 col-form-label">Phone</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="phone" id="phone" placeholder="Phone">
	</div>
</div>
<div class="row mb-3">
	<label for="email" class="col-sm-2 col-form-label">Email</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="email" id="email" placeholder="Email">
	</div>
</div>
<div class="row mb-3">
	<label for="table_number" class="col-sm-2 col-form-label">Table Number</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="table_number" id="table_number" placeholder="Table Number">
	</div>
</div>
<div class="row mb-3">
	<label for="guests_count" class="col-sm-2 col-form-label">Guests Count</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="guests_count" id="guests_count" placeholder="Guests Count">
	</div>
</div>
<div class="row mb-3">
	<label for="status" class="col-sm-2 col-form-label">Status</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="status" id="status" placeholder="Status">
	</div>
</div>
<div class="row mb-3">
	<label for="special_requests" class="col-sm-2 col-form-label">Special Requests</label>
	<div class="col-sm-10">
		<textarea class="form-control" name="special_requests" id="special_requests" placeholder="Special Requests"></textarea>
	</div>
</div>

<button type="submit" class="btn btn-primary">Save</button>
</form>
@endsection
@section('script')


@endsection
