<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/reservation/_show.blade.php" was generated by ProBot AI.
* Date: 3/5/2025 10:53:26 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show Reservation')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('reservations.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$reservation->id}}</td></tr>
		<tr><th>Name</th><td>{{$reservation->name}}</td></tr>
		<tr><th>Phone</th><td>{{$reservation->phone}}</td></tr>
		<tr><th>Email</th><td>{{$reservation->email}}</td></tr>
		<tr><th>Date</th><td>{{$reservation->date}}</td></tr>
		<tr><th>Time</th><td>{{$reservation->time}}</td></tr>
		<tr><th>Members</th><td>{{$reservation->members}}</td></tr>
		<tr><th>Special Requests</th><td>{{$reservation->special_requests}}</td></tr>
		<tr><th>Table Id</th><td>{{$reservation->table_id}}</td></tr>
		<tr><th>Created At</th><td>{{$reservation->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$reservation->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
