<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/inventory/_create.blade.php" was generated by ProBot AI.
* Date: 2/21/2025 12:56:02 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Create Inventory')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('inventorys.index')}}">Manage</a>
<form action="{{route('inventorys.store')}}" method ="post" enctype="multipart/form-data">
@csrf
<div class="row mb-3">
	<label for="product_id" class="col-sm-2 col-form-label">Product</label>
	<div class="col-sm-10">
		<select class="form-control" name="product_id" id="product_id">
			@foreach($products as $product)
				<option value="{{$product->id}}">{{$product->name}}</option>
			@endforeach
		</select>
	</div>
</div>
{{-- <div class="row mb-3">
	<label for="supplier_id" class="col-sm-2 col-form-label">Supplier</label>
	<div class="col-sm-10">
		<select class="form-control" name="supplier_id" id="supplier_id">
			@foreach($suppliers as $supplier)
				<option value="{{$supplier->id}}">{{$supplier->name}}</option>
			@endforeach
		</select>
	</div>
</div> --}}
<div class="row mb-3">
	<label for="quantity" class="col-sm-2 col-form-label">Quantity</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="quantity" id="quantity" placeholder="Quantity">
	</div>
</div>
{{-- <div class="row mb-3">
	<label for="unit_price" class="col-sm-2 col-form-label">Unit Price</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="unit_price" id="unit_price" placeholder="Unit Price">
	</div>
</div> --}}
<div class="row mb-3">
	<label for="expiry_date" class="col-sm-2 col-form-label">Expiry Date</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="expiry_date" id="expiry_date" placeholder="Expiry Date">
	</div>
</div>

<button type="submit" class="btn btn-primary">Save</button>
</form>
@endsection
@section('script')


@endsection
