<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/inventory/_edit.blade.php" was generated by ProBot AI.
* Date: 2/21/2025 12:56:02 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Edit Inventory')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('inventorys.index')}}">Manage</a>
<form action="{{route('inventorys.update',$inventory)}}" method ="post" enctype="multipart/form-data">
@csrf
@method("PUT")
<div class="row mb-3">
	<label for="product_id" class="col-sm-2 col-form-label">Product</label>
	<div class="col-sm-10">
		<select class="form-control" name="product_id" id="product_id">
			@foreach($products as $product)
				@if($product->id==$inventory->product_id)
					<option value="{{$product->id}}" selected>{{$product->name}}</option>
				@else
					<option value="{{$product->id}}">{{$product->name}}</option>
				@endif
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="supplier_id" class="col-sm-2 col-form-label">Supplier</label>
	<div class="col-sm-10">
		<select class="form-control" name="supplier_id" id="supplier_id">
			@foreach($suppliers as $supplier)
				@if($supplier->id==$inventory->supplier_id)
					<option value="{{$supplier->id}}" selected>{{$supplier->name}}</option>
				@else
					<option value="{{$supplier->id}}">{{$supplier->name}}</option>
				@endif
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="quantity" class="col-sm-2 col-form-label">Quantity</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="quantity" value="{{$inventory->quantity}}" id="quantity" placeholder="Quantity">
	</div>
</div>
<div class="row mb-3">
	<label for="unit_price" class="col-sm-2 col-form-label">Unit Price</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="unit_price" value="{{$inventory->unit_price}}" id="unit_price" placeholder="Unit Price">
	</div>
</div>
<div class="row mb-3">
	<label for="expiry_date" class="col-sm-2 col-form-label">Expiry Date</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="expiry_date" value="{{$inventory->expiry_date}}" id="expiry_date" placeholder="Expiry Date">
	</div>
</div>

<button type="submit" class="btn btn-primary">Save Change</button>
</form>
@endsection
@section('script')


@endsection
