<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/inventory/_index.blade.php" was generated by ProBot AI.
* Date: 2/21/2025 12:56:02 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage Inventory')
@section('style')


@endsection
@section('page')
<a href="{{route('inventorys.create')}}">New Inventory</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Product Id</th>
			<th>Supplier Id</th>
			<th>Quantity</th>
			<th>Unit Price</th>
			<th>Expiry Date</th>
			<th>Created At</th>
			<th>Updated At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($inventorys as $inventory)
		<tr>
			<td>{{$inventory->id}}</td>
			<td>{{$inventory->product_id}}</td>
			<td>{{$inventory->supplier_id}}</td>
			<td>{{$inventory->quantity}}</td>
			<td>{{$inventory->unit_price}}</td>
			<td>{{$inventory->expiry_date}}</td>
			<td>{{$inventory->created_at}}</td>
			<td>{{$inventory->updated_at}}</td>

			<td>
			<form action = "{{route('inventorys.destroy',$inventory->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('inventorys.show',$inventory->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('inventorys.edit',$inventory->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
