<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/inventory/_show.blade.php" was generated by ProBot AI.
* Date: 2/21/2025 12:56:02 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show Inventory')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('inventorys.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$inventory->id}}</td></tr>
		<tr><th>Product Id</th><td>{{$inventory->product_id}}</td></tr>
		{{-- <tr><th>Supplier Id</th><td>{{$inventory->supplier_id}}</td></tr> --}}
		<tr><th>Quantity</th><td>{{$inventory->quantity}}</td></tr>
		{{-- <tr><th>Unit Price</th><td>{{$inventory->unit_price}}</td></tr> --}}
		<tr><th>Expiry Date</th><td>{{$inventory->expiry_date}}</td></tr>
		<tr><th>Created At</th><td>{{$inventory->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$inventory->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
