<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_CustomerReviewController.php" was generated by ProBot AI.
* Date: 2/21/2025 12:55:30 AM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\CustomerReview;
use App\Models\Customer;
use App\Models\Product;
use App\Models\Order;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class CustomerReviewController extends Controller{
	public function index(){
		$customerreviews = CustomerReview::paginate(10);
		return view("pages.erp.customerreview.index",["customerreviews"=>$customerreviews]);
	}
	public function create(){
		return view("pages.erp.customerreview.create",["customers"=>Customer::all(),"products"=>Product::all(),"orders"=>Order::all()]);
	}
	public function store(Request $request){
		//CustomerReview::create($request->all());
		$customerreview = new CustomerReview;
		$customerreview->customer_id=$request->customer_id;
		$customerreview->product_id=$request->product_id;
		$customerreview->order_id=$request->order_id;
		$customerreview->rating=$request->rating;
		$customerreview->review=$request->review;
date_default_timezone_set("Asia/Dhaka");
		$customerreview->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$customerreview->updated_at=date('Y-m-d H:i:s');

		$customerreview->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$customerreview = CustomerReview::find($id);
		return view("pages.erp.customerreview.show",["customerreview"=>$customerreview]);
	}
	public function edit(CustomerReview $customerreview){
		return view("pages.erp.customerreview.edit",["customerreview"=>$customerreview,"customers"=>Customer::all(),"products"=>Product::all(),"orders"=>Order::all()]);
	}
	public function update(Request $request,CustomerReview $customerreview){
		//CustomerReview::update($request->all());
		$customerreview = CustomerReview::find($customerreview->id);
		$customerreview->customer_id=$request->customer_id;
		$customerreview->product_id=$request->product_id;
		$customerreview->order_id=$request->order_id;
		$customerreview->rating=$request->rating;
		$customerreview->review=$request->review;
date_default_timezone_set("Asia/Dhaka");
		$customerreview->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$customerreview->updated_at=date('Y-m-d H:i:s');

		$customerreview->save();

		return redirect()->route("customerreviews.index")->with('success','Updated Successfully.');
	}
	public function destroy(CustomerReview $customerreview){
		$customerreview->delete();
		return redirect()->route("customerreviews.index")->with('success', 'Deleted Successfully.');
	}
}
?>
