<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_MenuItemController.php" was generated by ProBot AI.
* Date: 2/21/2025 1:15:24 AM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\MenuItem;
use App\Models\Menus;
use App\Models\Product;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class MenuItemController extends Controller{
	public function index(){
		$menuitems = MenuItem::paginate(10);
		return view("pages.erp.menuitem.index",["menuitems"=>$menuitems]);
	}
	public function create(){
		return view("pages.erp.menuitem.create",["menuss"=>Menus::all(),"products"=>Product::all()]);
	}
	public function store(Request $request){
		//MenuItem::create($request->all());
		$menuitem = new MenuItem;
		$menuitem->menus_id=$request->menus_id;
		$menuitem->product_id=$request->product_id;
		$menuitem->price=$request->price;
		$menuitem->is_available=$request->is_available;
date_default_timezone_set("Asia/Dhaka");
		$menuitem->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$menuitem->updated_at=date('Y-m-d H:i:s');

		$menuitem->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$menuitem = MenuItem::find($id);
		return view("pages.erp.menuitem.show",["menuitem"=>$menuitem]);
	}
	public function edit(MenuItem $menuitem){
		return view("pages.erp.menuitem.edit",["menuitem"=>$menuitem,"menuss"=>Menus::all(),"products"=>Product::all()]);
	}
	public function update(Request $request,MenuItem $menuitem){
		//MenuItem::update($request->all());
		$menuitem = MenuItem::find($menuitem->id);
		$menuitem->menus_id=$request->menus_id;
		$menuitem->product_id=$request->product_id;
		$menuitem->price=$request->price;
		$menuitem->is_available=$request->is_available;
date_default_timezone_set("Asia/Dhaka");
		$menuitem->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$menuitem->updated_at=date('Y-m-d H:i:s');

		$menuitem->save();

		return redirect()->route("menuitems.index")->with('success','Updated Successfully.');
	}
	public function destroy(MenuItem $menuitem){
		$menuitem->delete();
		return redirect()->route("menuitems.index")->with('success', 'Deleted Successfully.');
	}
}
?>
