<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_MenuItemController.php" was generated by ProBot AI.
* Date: 2/19/2025 11:46:38 PM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\MenuItem;
use App\Models\Category;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class MenuItemController extends Controller{
	public function index(){
		$menuitems = MenuItem::paginate(10);
		return view("pages.erp.menuitem.index",["menuitems"=>$menuitems]);
	}
	public function create(){
		return view("pages.erp.menuitem.create",["categories"=>Category::all()]);
	}
	public function store(Request $request){
		//MenuItem::create($request->all());
		$menuitem = new MenuItem;
		$menuitem->name=$request->name;
		$menuitem->category_id=$request->category_id;
		if(isset($request->photo)){
			$menuitem->photo=$request->photo;
		}
		$menuitem->purchase_price=$request->purchase_price;
		$menuitem->selling_price=$request->selling_price;
		$menuitem->min_stock_level=$request->min_stock_level;
		$menuitem->unit=$request->unit;
date_default_timezone_set("Asia/Dhaka");
		$menuitem->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$menuitem->updated_at=date('Y-m-d H:i:s');

		$menuitem->save();
		if(isset($request->photo)){
			$imageName=$menuitem->id.'.'.$request->photo->extension();
			$menuitem->photo=$imageName;
			$menuitem->update();
			$request->photo->move(public_path('img'),$imageName);
		}

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$menuitem = MenuItem::find($id);
		return view("pages.erp.menuitem.show",["menuitem"=>$menuitem]);
	}
	public function edit(MenuItem $menuitem){
		return view("pages.erp.menuitem.edit",["menuitem"=>$menuitem,"categories"=>Category::all()]);
	}
	public function update(Request $request,MenuItem $menuitem){
		//MenuItem::update($request->all());
		$menuitem = MenuItem::find($menuitem->id);
		$menuitem->name=$request->name;
		$menuitem->category_id=$request->category_id;
		if(isset($request->photo)){
			$menuitem->photo=$request->photo;
		}
		$menuitem->purchase_price=$request->purchase_price;
		$menuitem->selling_price=$request->selling_price;
		$menuitem->min_stock_level=$request->min_stock_level;
		$menuitem->unit=$request->unit;
date_default_timezone_set("Asia/Dhaka");
		$menuitem->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$menuitem->updated_at=date('Y-m-d H:i:s');

		$menuitem->save();
		if(isset($request->photo)){
			$imageName=$menuitem->id.'.'.$request->photo->extension();
			$menuitem->photo=$imageName;
			$menuitem->update();
			$request->photo->move(public_path('img'),$imageName);
		}

		return redirect()->route("menuitems.index")->with('success','Updated Successfully.');
	}
	public function destroy(MenuItem $menuitem){
		$menuitem->delete();
		return redirect()->route("menuitems.index")->with('success', 'Deleted Successfully.');
	}
}
?>
