<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_MenuController.php" was generated by ProBot AI.
* Date: 2/21/2025 1:14:56 AM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\Menu;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class MenuController extends Controller{
	public function index(){
		$menus = Menu::paginate(10);
		return view("pages.erp.menu.index",["menus"=>$menus]);
	}
	public function create(){
		return view("pages.erp.menu.create",[]);
	}
	public function store(Request $request){
		//Menu::create($request->all());
		$menu = new Menu;
		$menu->name=$request->name;
		$menu->description=$request->description;
		$menu->is_active=$request->is_active;
date_default_timezone_set("Asia/Dhaka");
		$menu->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$menu->updated_at=date('Y-m-d H:i:s');

		$menu->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$menu = Menu::find($id);
		return view("pages.erp.menu.show",["menu"=>$menu]);
	}
	public function edit(Menu $menu){
		return view("pages.erp.menu.edit",["menu"=>$menu,]);
	}
	public function update(Request $request,Menu $menu){
		//Menu::update($request->all());
		$menu = Menu::find($menu->id);
		$menu->name=$request->name;
		$menu->description=$request->description;
		$menu->is_active=$request->is_active;
date_default_timezone_set("Asia/Dhaka");
		$menu->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$menu->updated_at=date('Y-m-d H:i:s');

		$menu->save();

		return redirect()->route("menus.index")->with('success','Updated Successfully.');
	}
	public function destroy(Menu $menu){
		$menu->delete();
		return redirect()->route("menus.index")->with('success', 'Deleted Successfully.');
	}
}
?>
