<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_PaymentStatuController.php" was generated by ProBot AI.
* Date: 2/21/2025 12:59:18 AM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\PaymentStatu;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class PaymentStatuController extends Controller{
	public function index(){
		$paymentstatus = PaymentStatu::paginate(10);
		return view("pages.erp.paymentstatu.index",["paymentstatus"=>$paymentstatus]);
	}
	public function create(){
		return view("pages.erp.paymentstatu.create",[]);
	}
	public function store(Request $request){
		//PaymentStatu::create($request->all());
		$paymentstatu = new PaymentStatu;
		$paymentstatu->status=$request->status;
		$paymentstatu->description=$request->description;
date_default_timezone_set("Asia/Dhaka");
		$paymentstatu->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$paymentstatu->updated_at=date('Y-m-d H:i:s');

		$paymentstatu->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$paymentstatu = PaymentStatu::find($id);
		return view("pages.erp.paymentstatu.show",["paymentstatu"=>$paymentstatu]);
	}
	public function edit(PaymentStatu $paymentstatu){
		return view("pages.erp.paymentstatu.edit",["paymentstatu"=>$paymentstatu,]);
	}
	public function update(Request $request,PaymentStatu $paymentstatu){
		//PaymentStatu::update($request->all());
		$paymentstatu = PaymentStatu::find($paymentstatu->id);
		$paymentstatu->status=$request->status;
		$paymentstatu->description=$request->description;
date_default_timezone_set("Asia/Dhaka");
		$paymentstatu->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$paymentstatu->updated_at=date('Y-m-d H:i:s');

		$paymentstatu->save();

		return redirect()->route("paymentstatus.index")->with('success','Updated Successfully.');
	}
	public function destroy(PaymentStatu $paymentstatu){
		$paymentstatu->delete();
		return redirect()->route("paymentstatus.index")->with('success', 'Deleted Successfully.');
	}
}
?>
