<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_ReservationController.php" was generated by ProBot AI.
* Date: 2/27/2025 12:25:06 PM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\Reservation;
use App\Models\Customer;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class ReservationController extends Controller{
	public function index(){
		$reservations = Reservation::paginate(10);
		return view("pages.erp.reservation.index",["reservations"=>$reservations]);
	}
	public function create(){
		return view("pages.erp.reservation.create",["customers"=>Customer::all()]);
	}
	public function store(Request $request){
		//Reservation::create($request->all());
		$reservation = new Reservation;
		$reservation->customer_id=$request->customer_id;
		$reservation->booking_name=$request->booking_name;
		$reservation->phone=$request->phone;
		$reservation->email=$request->email;
		$reservation->table_number=$request->table_number;
		$reservation->guests_count=$request->guests_count;
		$reservation->reservation_date=$request->reservation_date;
		$reservation->status=$request->status;
		$reservation->special_requests=$request->special_requests;
date_default_timezone_set("Asia/Dhaka");
		$reservation->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$reservation->updated_at=date('Y-m-d H:i:s');

		$reservation->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$reservation = Reservation::find($id);
		return view("pages.erp.reservation.show",["reservation"=>$reservation]);
	}
	public function edit(Reservation $reservation){
		return view("pages.erp.reservation.edit",["reservation"=>$reservation,"customers"=>Customer::all()]);
	}
	public function update(Request $request,Reservation $reservation){
		//Reservation::update($request->all());
		$reservation = Reservation::find($reservation->id);
		$reservation->customer_id=$request->customer_id;
		$reservation->booking_name=$request->booking_name;
		$reservation->phone=$request->phone;
		$reservation->email=$request->email;
		$reservation->table_number=$request->table_number;
		$reservation->guests_count=$request->guests_count;
		$reservation->reservation_date=$request->reservation_date;
		$reservation->status=$request->status;
		$reservation->special_requests=$request->special_requests;
date_default_timezone_set("Asia/Dhaka");
		$reservation->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$reservation->updated_at=date('Y-m-d H:i:s');

		$reservation->save();

		return redirect()->route("reservations.index")->with('success','Updated Successfully.');
	}
	public function destroy(Reservation $reservation){
		$reservation->delete();
		return redirect()->route("reservations.index")->with('success', 'Deleted Successfully.');
	}
}
?>
