<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_RestableDurationController.php" was generated by ProBot AI.
* Date: 3/12/2025 10:00:16 AM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\RestableDuration;
use App\Models\Res_Table;
use App\Models\ResTable;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class RestableDurationController extends Controller{
	public function index(){
		$restabledurations = RestableDuration::paginate(10);
		return view("pages.erp.restableduration.index",["restabledurations"=>$restabledurations]);
	}
	public function create(){
		return view("pages.erp.restableduration.create",["res_tables"=>ResTable::all()]);
	}
	public function store(Request $request){
		//RestableDuration::create($request->all());
		$restableduration = new RestableDuration;
		$restableduration->res_table_id=$request->res_table_id;
		$restableduration->start_time=$request->start_time;
		$restableduration->end_time=$request->end_time;
date_default_timezone_set("Asia/Dhaka");
		$restableduration->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$restableduration->updated_at=date('Y-m-d H:i:s');

		$restableduration->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$restableduration = RestableDuration::find($id);
		return view("pages.erp.restableduration.show",["restableduration"=>$restableduration]);
	}
	public function edit(RestableDuration $restableduration){
		return view("pages.erp.restableduration.edit",["restableduration"=>$restableduration,"res_tables"=>ResTable::all()]);
	}
	public function update(Request $request,RestableDuration $restableduration){
		//RestableDuration::update($request->all());
		$restableduration = RestableDuration::find($restableduration->id);
		$restableduration->res_table_id=$request->res_table_id;
		$restableduration->start_time=$request->start_time;
		$restableduration->end_time=$request->end_time;
date_default_timezone_set("Asia/Dhaka");
		$restableduration->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$restableduration->updated_at=date('Y-m-d H:i:s');

		$restableduration->save();

		return redirect()->route("restabledurations.index")->with('success','Updated Successfully.');
	}
	public function destroy(RestableDuration $restableduration){
		$restableduration->delete();
		return redirect()->route("restabledurations.index")->with('success', 'Deleted Successfully.');
	}
}
?>
