<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_StaffController.php" was generated by ProBot AI.
* Date: 2/21/2025 12:54:55 AM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\Staff;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class StaffController extends Controller{
	public function index(){
		$staffs = Staff::paginate(10);
		return view("pages.erp.staff.index",["staffs"=>$staffs]);
	}
	public function create(){
		return view("pages.erp.staff.create",[]);
	}
	public function store(Request $request){
		//Staff::create($request->all());
		$staff = new Staff;
		$staff->name=$request->name;
		if(isset($request->photo)){
			$staff->photo=$request->photo;
		}
		$staff->phone=$request->phone;
		$staff->email=$request->email;
		$staff->position=$request->position;
		$staff->status=$request->status;
date_default_timezone_set("Asia/Dhaka");
		$staff->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$staff->updated_at=date('Y-m-d H:i:s');

		$staff->save();
		if(isset($request->photo)){
			$imageName=$staff->id.'.'.$request->photo->extension();
			$staff->photo=$imageName;
			$staff->update();
			$request->photo->move(public_path('img'),$imageName);
		}

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$staff = Staff::find($id);
		return view("pages.erp.staff.show",["staff"=>$staff]);
	}
	public function edit(Staff $staff){
		return view("pages.erp.staff.edit",["staff"=>$staff,]);
	}
	public function update(Request $request,Staff $staff){
		//Staff::update($request->all());
		$staff = Staff::find($staff->id);
		$staff->name=$request->name;
		if(isset($request->photo)){
			$staff->photo=$request->photo;
		}
		$staff->phone=$request->phone;
		$staff->email=$request->email;
		$staff->position=$request->position;
		$staff->status=$request->status;
date_default_timezone_set("Asia/Dhaka");
		$staff->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$staff->updated_at=date('Y-m-d H:i:s');

		$staff->save();
		if(isset($request->photo)){
			$imageName=$staff->id.'.'.$request->photo->extension();
			$staff->photo=$imageName;
			$staff->update();
			$request->photo->move(public_path('img'),$imageName);
		}

		return redirect()->route("staffs.index")->with('success','Updated Successfully.');
	}
	public function destroy(Staff $staff){
		$staff->delete();
		return redirect()->route("staffs.index")->with('success', 'Deleted Successfully.');
	}
}
?>
