<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_StatuController.php" was generated by ProBot AI.
* Date: 2/20/2025 10:31:49 AM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\Statu;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class StatuController extends Controller{
	public function index(){
		$status = Statu::paginate(10);
		return view("pages.erp.statu.index",["status"=>$status]);
	}
	public function create(){
		return view("pages.erp.statu.create",[]);
	}
	public function store(Request $request){
		//Statu::create($request->all());
		$statu = new Statu;
		$statu->name=$request->name;
		$statu->description=$request->description;
date_default_timezone_set("Asia/Dhaka");
		$statu->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$statu->updated_at=date('Y-m-d H:i:s');

		$statu->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$statu = Statu::find($id);
		return view("pages.erp.statu.show",["statu"=>$statu]);
	}
	public function edit(Statu $statu){
		return view("pages.erp.statu.edit",["statu"=>$statu,]);
	}
	public function update(Request $request,Statu $statu){
		//Statu::update($request->all());
		$statu = Statu::find($statu->id);
		$statu->name=$request->name;
		$statu->description=$request->description;
date_default_timezone_set("Asia/Dhaka");
		$statu->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$statu->updated_at=date('Y-m-d H:i:s');

		$statu->save();

		return redirect()->route("status.index")->with('success','Updated Successfully.');
	}
	public function destroy(Statu $statu){
		$statu->delete();
		return redirect()->route("status.index")->with('success', 'Deleted Successfully.');
	}
}
?>
