<?php
/*
* ProBot Version: 4.0
* Laravel Version: 10x
* Description: This source file "app/Models/_ResTable.php" was generated by ProBot AI.
* Date: 3/11/2025 10:47:29 AM
* Contact: towhid1@outlook.com
*/
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
class ResTable extends Model{


}
?>
