<?php
/*
* ProBot Version: 4.0
* Laravel Version: 10x
* Description: This source file "app/Models/_Customer.php" was generated by ProBot AI.
* Date: 3/1/2025 12:21:59 AM
* Contact: towhid1@outlook.com
*/
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
class Customer extends Model{


}
?>
