<?php
/*
* ProBot Version: 4.0
* Laravel Version: 10x
* Description: This source file "app/Models/_OrderItem.php" was generated by ProBot AI.
* Date: 2/21/2025 12:56:59 AM
* Contact: towhid1@outlook.com
*/
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
class OrderItem extends Model{

    public function product()
    {
        return $this->belongsTo(Product::class, 'product_id');
    }


}
?>
