<?php
/*
* ProBot Version: 4.0
* Laravel Version: 10x
* Description: This source file "app/Models/_PaymentMethod.php" was generated by ProBot AI.
* Date: 2/21/2025 12:59:00 AM
* Contact: towhid1@outlook.com
*/
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
class PaymentMethod extends Model{


}
?>
