<?php
/*
* ProBot Version: 4.0
* Laravel Version: 10x
* Description: This source file "app/Models/_Reservation.php" was generated by ProBot AI.
* Date: 2/27/2025 12:25:07 PM
* Contact: towhid1@outlook.com
*/
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
class Reservation extends Model{


}
?>
