<?php
/*
* ProBot Version: 4.0
* Laravel Version: 10x
* Description: This source file "app/Models/_RestableDuration.php" was generated by ProBot AI.
* Date: 3/12/2025 10:00:19 AM
* Contact: towhid1@outlook.com
*/
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
class RestableDuration extends Model{


}
?>
