<?php
/*
* ProBot Version: 4.0
* Laravel Version: 10x
* Description: This source file "app/Models/_Statu.php" was generated by ProBot AI.
* Date: 2/20/2025 10:31:50 AM
* Contact: towhid1@outlook.com
*/

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Statu extends Model
{

    protected $table = "status";
}
