<?php
/*
* ProBot Version: 4.0
* Laravel Version: 10x
* Description: This source file "app/Models/_Supplier.php" was generated by ProBot AI.
* Date: 2/19/2025 11:51:42 PM
* Contact: towhid1@outlook.com
*/
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
class Supplier extends Model{


}
?>
