<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/menuitem/_create.blade.php" was generated by ProBot AI.
* Date: 2/19/2025 11:46:41 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Create MenuItem')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('menuitems.index')}}">Manage</a>
<form action="{{route('menuitems.store')}}" method ="post" enctype="multipart/form-data">
@csrf
<div class="row mb-3">
	<label for="name" class="col-sm-2 col-form-label">Name</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="name" id="name" placeholder="Name">
	</div>
</div>
<div class="row mb-3">
	<label for="category_id" class="col-sm-2 col-form-label">Category</label>
	<div class="col-sm-10">
		<select class="form-control" name="category_id" id="category_id">
			@foreach($categories as $category)
				<option value="{{$category->id}}">{{$category->name}}</option>
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="photo" class="col-sm-2 col-form-label">Photo</label>
	<div class="col-sm-10">
		<input type = "file" class="form-control" name="photo" id="photo" placeholder="Photo">
	</div>
</div>
<div class="row mb-3">
	<label for="purchase_price" class="col-sm-2 col-form-label">Purchase Price</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="purchase_price" id="purchase_price" placeholder="Purchase Price">
	</div>
</div>
<div class="row mb-3">
	<label for="selling_price" class="col-sm-2 col-form-label">Selling Price</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="selling_price" id="selling_price" placeholder="Selling Price">
	</div>
</div>
<div class="row mb-3">
	<label for="min_stock_level" class="col-sm-2 col-form-label">Min Stock Level</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="min_stock_level" id="min_stock_level" placeholder="Min Stock Level">
	</div>
</div>
<div class="row mb-3">
	<label for="unit" class="col-sm-2 col-form-label">Unit</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="unit" id="unit" placeholder="Unit">
	</div>
</div>

<button type="submit" class="btn btn-primary">Save</button>
</form>
@endsection
@section('script')


@endsection
