<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/menuitem/_edit.blade.php" was generated by ProBot AI.
* Date: 2/21/2025 1:15:25 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Edit MenuItem')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('menuitems.index')}}">Manage</a>
<form action="{{route('menuitems.update',$menuitem)}}" method ="post" enctype="multipart/form-data">
@csrf
@method("PUT")
<div class="row mb-3">
	<label for="menus_id" class="col-sm-2 col-form-label">Menus</label>
	<div class="col-sm-10">
		<select class="form-control" name="menus_id" id="menus_id">
			@foreach($menuss as $menus)
				@if($menus->id==$menuitem->menus_id)
					<option value="{{$menus->id}}" selected>{{$menus->name}}</option>
				@else
					<option value="{{$menus->id}}">{{$menus->name}}</option>
				@endif
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="product_id" class="col-sm-2 col-form-label">Product</label>
	<div class="col-sm-10">
		<select class="form-control" name="product_id" id="product_id">
			@foreach($products as $product)
				@if($product->id==$menuitem->product_id)
					<option value="{{$product->id}}" selected>{{$product->name}}</option>
				@else
					<option value="{{$product->id}}">{{$product->name}}</option>
				@endif
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="price" class="col-sm-2 col-form-label">Price</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="price" value="{{$menuitem->price}}" id="price" placeholder="Price">
	</div>
</div>

<button type="submit" class="btn btn-primary">Save Change</button>
</form>
@endsection
@section('script')


@endsection
