<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/menuitem/_index.blade.php" was generated by ProBot AI.
* Date: 2/19/2025 11:46:41 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage MenuItem')
@section('style')


@endsection
@section('page')
<a href="{{route('menuitems.create')}}">New MenuItem</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Name</th>
			<th>Category Id</th>
			<th>Photo</th>
			<th>Purchase Price</th>
			<th>Selling Price</th>
			<th>Min Stock Level</th>
			<th>Unit</th>
			<th>Created At</th>
			<th>Updated At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($menuitems as $menuitem)
		<tr>
			<td>{{$menuitem->id}}</td>
			<td>{{$menuitem->name}}</td>
			<td>{{$menuitem->category_id}}</td>
			<td><img src="{{asset('img/'.$menuitem->photo)}}" width="100" /></td>
			<td>{{$menuitem->purchase_price}}</td>
			<td>{{$menuitem->selling_price}}</td>
			<td>{{$menuitem->min_stock_level}}</td>
			<td>{{$menuitem->unit}}</td>
			<td>{{$menuitem->created_at}}</td>
			<td>{{$menuitem->updated_at}}</td>

			<td>
			<form action = "{{route('menuitems.destroy',$menuitem->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('menuitems.show',$menuitem->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('menuitems.edit',$menuitem->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
