<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/menuitem/_index.blade.php" was generated by ProBot AI.
* Date: 2/21/2025 1:15:25 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage MenuItem')
@section('style')


@endsection
@section('page')
<a href="{{route('menuitems.create')}}">New MenuItem</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Menus Id</th>
			<th>Product Id</th>
			<th>Price</th>
			<th>Is Available</th>
			<th>Created At</th>
			<th>Updated At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($menuitems as $menuitem)
		<tr>
			<td>{{$menuitem->id}}</td>
			<td>{{$menuitem->menus_id}}</td>
			<td>{{$menuitem->product_id}}</td>
			<td>{{$menuitem->price}}</td>
			<td>{{$menuitem->is_available}}</td>
			<td>{{$menuitem->created_at}}</td>
			<td>{{$menuitem->updated_at}}</td>

			<td>
			<form action = "{{route('menuitems.destroy',$menuitem->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('menuitems.show',$menuitem->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('menuitems.edit',$menuitem->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
