<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/menuitem/_show.blade.php" was generated by ProBot AI.
* Date: 2/19/2025 11:46:41 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show MenuItem')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('menuitems.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$menuitem->id}}</td></tr>
		<tr><th>Name</th><td>{{$menuitem->name}}</td></tr>
		<tr><th>Category Id</th><td>{{$menuitem->category_id}}</td></tr>
		<tr><th>Photo</th><td><img src="{{asset('img/'.$menuitem->photo)}}" width="100" /></td></tr>
		<tr><th>Purchase Price</th><td>{{$menuitem->purchase_price}}</td></tr>
		<tr><th>Selling Price</th><td>{{$menuitem->selling_price}}</td></tr>
		<tr><th>Min Stock Level</th><td>{{$menuitem->min_stock_level}}</td></tr>
		<tr><th>Unit</th><td>{{$menuitem->unit}}</td></tr>
		<tr><th>Created At</th><td>{{$menuitem->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$menuitem->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
