<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/menuitem/_show.blade.php" was generated by ProBot AI.
* Date: 2/21/2025 1:15:25 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show MenuItem')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('menuitems.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$menuitem->id}}</td></tr>
		<tr><th>Menus Id</th><td>{{$menuitem->menus_id}}</td></tr>
		<tr><th>Product Id</th><td>{{$menuitem->product_id}}</td></tr>
		<tr><th>Price</th><td>{{$menuitem->price}}</td></tr>
		<tr><th>Is Available</th><td>{{$menuitem->is_available}}</td></tr>
		<tr><th>Created At</th><td>{{$menuitem->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$menuitem->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
