<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/payment/_edit.blade.php" was generated by ProBot AI.
* Date: 2/20/2025 12:37:55 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Edit Payment')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('payments.index')}}">Manage</a>
<form action="{{route('payments.update',$payment)}}" method ="post" enctype="multipart/form-data">
@csrf
@method("PUT")
<div class="row mb-3">
	<label for="transaction_type" class="col-sm-2 col-form-label">Transaction Type</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="transaction_type" value="{{$payment->transaction_type}}" id="transaction_type" placeholder="Transaction Type">
	</div>
</div>
<div class="row mb-3">
	<label for="transaction_id" class="col-sm-2 col-form-label">Transaction</label>
	<div class="col-sm-10">
		<select class="form-control" name="transaction_id" id="transaction_id">
			@foreach($transactions as $transaction)
				@if($transaction->id==$payment->transaction_id)
					<option value="{{$transaction->id}}" selected>{{$transaction->name}}</option>
				@else
					<option value="{{$transaction->id}}">{{$transaction->name}}</option>
				@endif
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="amount_paid" class="col-sm-2 col-form-label">Amount Paid</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="amount_paid" value="{{$payment->amount_paid}}" id="amount_paid" placeholder="Amount Paid">
	</div>
</div>
<div class="row mb-3">
	<label for="payment_date" class="col-sm-2 col-form-label">Payment Date</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="payment_date" value="{{$payment->payment_date}}" id="payment_date" placeholder="Payment Date">
	</div>
</div>

<button type="submit" class="btn btn-primary">Save Change</button>
</form>
@endsection
@section('script')


@endsection
