<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/payment/_show.blade.php" was generated by ProBot AI.
* Date: 2/20/2025 12:37:55 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show Payment')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('payments.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$payment->id}}</td></tr>
		<tr><th>Transaction Type</th><td>{{$payment->transaction_type}}</td></tr>
		<tr><th>Transaction Id</th><td>{{$payment->transaction_id}}</td></tr>
		<tr><th>Amount Paid</th><td>{{$payment->amount_paid}}</td></tr>
		<tr><th>Payment Date</th><td>{{$payment->payment_date}}</td></tr>
		<tr><th>Created At</th><td>{{$payment->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$payment->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
