<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/payment/_edit.blade.php" was generated by ProBot AI.
* Date: 3/1/2025 9:37:43 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Edit Payment')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('payments.index')}}">Manage</a>
<form action="{{route('payments.update',$payment)}}" method ="post" enctype="multipart/form-data">
@csrf
@method("PUT")
<div class="row mb-3">
	<label for="order_id" class="col-sm-2 col-form-label">Order</label>
	<div class="col-sm-10">
		<select class="form-control" name="order_id" id="order_id">
			@foreach($orders as $order)
				@if($order->id==$payment->order_id)
					<option value="{{$order->id}}" selected>{{$order->name}}</option>
				@else
					<option value="{{$order->id}}">{{$order->name}}</option>
				@endif
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="customer_id" class="col-sm-2 col-form-label">Customer</label>
	<div class="col-sm-10">
		<select class="form-control" name="customer_id" id="customer_id">
			@foreach($customers as $customer)
				@if($customer->id==$payment->customer_id)
					<option value="{{$customer->id}}" selected>{{$customer->name}}</option>
				@else
					<option value="{{$customer->id}}">{{$customer->name}}</option>
				@endif
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="payment_method" class="col-sm-2 col-form-label">Payment Method</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="payment_method" value="{{$payment->payment_method}}" id="payment_method" placeholder="Payment Method">
	</div>
</div>
<div class="row mb-3">
	<label for="payment_status_id" class="col-sm-2 col-form-label">Payment_Status</label>
	<div class="col-sm-10">
		<select class="form-control" name="payment_status_id" id="payment_status_id">
			@foreach($payment_statuss as $payment_status)
				@if($payment_status->id==$payment->payment_status_id)
					<option value="{{$payment_status->id}}" selected>{{$payment_status->name}}</option>
				@else
					<option value="{{$payment_status->id}}">{{$payment_status->name}}</option>
				@endif
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="amount" class="col-sm-2 col-form-label">Amount</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="amount" value="{{$payment->amount}}" id="amount" placeholder="Amount">
	</div>
</div>
<div class="row mb-3">
	<label for="transaction_id" class="col-sm-2 col-form-label">Transaction Id</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="transaction_id" value="{{$payment->transaction_id}}" id="transaction_id" placeholder="Transaction Id">
	</div>
</div>

<button type="submit" class="btn btn-primary">Save Change</button>
</form>
@endsection
@section('script')


@endsection
