<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/paymentmethod/_index.blade.php" was generated by ProBot AI.
* Date: 2/21/2025 12:59:00 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage PaymentMethod')
@section('style')


@endsection
@section('page')
<a href="{{route('paymentmethods.create')}}">New PaymentMethod</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Method Name</th>
			<th>Details</th>
			<th>Created At</th>
			<th>Updated At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($paymentmethods as $paymentmethod)
		<tr>
			<td>{{$paymentmethod->id}}</td>
			<td>{{$paymentmethod->method_name}}</td>
			<td>{{$paymentmethod->details}}</td>
			<td>{{$paymentmethod->created_at}}</td>
			<td>{{$paymentmethod->updated_at}}</td>

			<td>
			<form action = "{{route('paymentmethods.destroy',$paymentmethod->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('paymentmethods.show',$paymentmethod->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('paymentmethods.edit',$paymentmethod->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
