<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/paymentmethod/_show.blade.php" was generated by ProBot AI.
* Date: 2/21/2025 12:59:00 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show PaymentMethod')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('paymentmethods.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$paymentmethod->id}}</td></tr>
		<tr><th>Method Name</th><td>{{$paymentmethod->method_name}}</td></tr>
		<tr><th>Details</th><td>{{$paymentmethod->details}}</td></tr>
		<tr><th>Created At</th><td>{{$paymentmethod->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$paymentmethod->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
